### ISSUE TITLE
find alternative for CAIQ reference for requirement P-030  

### ISSUE THREAD

**Issue by jdaoust** [nmfta-repo/nmfta-telematics_security_requirements#26]
The current reference to CAIQ BCR-01.2 for requirement P-030 refers to the outdated questionnaire CAIQ v3.0.1. The new version (CAIQ v3.1) doesn't seem to contain a direct replacement for the old BCR-01.2 question. Possible replacements include the new BCR-01.2 or other questions from the BCR-01 control.

 CAIQ v3.1 can be found attached below.
[CAIQ_v3.1_Final.xlsx](https://github.com/nmfta-repo/nmfta-telematics_security_requirements/files/6468539/CAIQ_v3.1_Final.xlsx)

**Comment by BenGardiner** [comment]
at the 20210614 meeting this was discussed and it was agreed to use BCR-01.6 and BCR-01.1  as references.
