### ISSUE TITLE
add xrefs to NIST 800-82

### ISSUE THREAD

**Issue by BenGardiner** [nmfta-repo/nmfta-telematics_security_requirements#39]
the segmentation guidelines in particular could be relevant c.f. *Guide to Industrial Control Systems (ICS) Security* https://csrc.nist.gov/publications/detail/sp/800-82/rev-2/final

**Comment by jstines01** [comment]
It's small but we submitted a [PR](https://github.com/nmfta-repo/vcr-experiment/pull/58) that adds some references to 800-82 around segmentation. We intend on continuing to review other guidelines/frameworks and making more PRs in small batches per-guideline basis. Will err on your judgement for if / when to call together the committee for review, but please do let us know if we're going in the right direction here or if we should adjust our process as we continue.

**Comment by BenGardiner** [comment]
resolved by https://github.com/nmfta-repo/nmfta-telematics_security_requirements/pull/48

thanks @jstines01 !
